### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by jostreff** [smilstea/IOS-XR-Maintenace-Window-Checker#5]
Hi,
As you know python2.7 is going on most UNIXes to obsolete state, because no more bug-fixes will be made on IT.
Currently I've solved the problems using autopep8 -i <on_both_python_programs> - but this brakes the git up of your source.

BR,
Jordan

**Comment by smilstea** [comment]
Thank you for your message, I have been in the process of upgrading my scripts. I had to rewrite paramiko for some reason as the byte to unicode conversation that normally happened automatically in python 2 did not happen in python3. Currently I am working with telnetlib3 and asyncio to get telnet support which means rewriting my entire telnet library as none of the functions are the same.

I have not touched the comparer script yet as I want to verify telnet and ssh work first especially on long outputs.

I expect to have v2.0.0 out by the end of the month with python3 support and quite a few logic changes on the comparer side.

Sam

**Comment by jostreff** [comment]
Interesting things happens when cisco devices are using tactics+ AAA in existing version. Looks like that ssh was authenticated, then session is disconnected for some reason. So for me it's great news that you are trying to rewrite the code to not use paramiko library.

BR,
Jordan

**Comment by smilstea** [comment]
implemented python3 support in release 2.0.0

**Comment by smilstea** [comment]
I finished the coding today and it seems to work, I should add in try
except clauses etc though to verify errors, right now its a catch all.
I managed to get it uploaded to github, so give it a try and let me know if
there are any issues.

Sam

**Comment by jostreff** [comment]
Hi Sam,

It’s really great that you have made the changes so fast! We have plans to use the tool in real world scenario, for verifying the upgrades to IOSXR 6.6.3SP4.
 
I have tried the new version it really doesn’t support exceptions - as it’s visible bellow:

$ python /usr/local/IOS-XR-Maintenance-Window-Checker/ios_xr_mw_gatherer.py --file /tmp/lab-1-pre.txt --ipv4addr 10.96.237.126 --username jostreff --ssh
Filename: /tmp/lab-1-pre.txt
Proceeding with login to router
Please enter your password:
Logging in, may take 30s before next output
SSH error End Of File (EOF). Empty string style platform.
<pexpect.pxssh.pxssh object at 0x8012adf50>
command: /usr/bin/ssh
args: ['/usr/bin/ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-q', '-l', 'jostreff', '10.96.237.126']
buffer (last 100 chars): b''
before (last 100 chars): b'show clock\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 20060
child_fd: 6
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b'RP\\S+#')
    1: TIMEOUT

$ python /usr/local/IOS-XR-Maintenance-Window-Checker/ios_xr_mw_gatherer.py --file /tmp/10.96.237.65.txt --ipv4addr 10.96.237.65 --username jordan.ostrev --ssh
Filename: /tmp/10.96.237.65.txt
Proceeding with login to router
Please enter your password:
Logging in, may take 30s before next output
Command 1 of 38 complete
Command 2 of 38 complete
SSH error 'ascii' codec can't decode byte 0xc2 in position 71709: ordinal not in range(128)

BR,
Jordan

**Comment by smilstea** [comment]
I think I fixed the ASCII issue, I can't reproduce it, but I believe my
issue is that I was not decoding from utf-8 like I should have been.
The first issue might be because of host key addition to SSH known hosts
file on the device, I made a change to use pexpect without pxssh and made
some additional changes to handle EOF etc. You might want to check if the
host is in ~/.ssh/known_hosts for the failing host (I assume its not) and
for the working host it probably is there, simply SSHing to the device from
bash and adding the cert will work or via my new code. I just removed the
known host on my server to test and added a print statement and it reached
that code and added the host and continued to the password prompt etc.
If you run into more issues feel free to open more 'issues' or email me
directly smilstea @ cisco . com.
The new code is up on master branch and branch 2.0.1.

Sam

**Comment by jostreff** [comment]
Hi Sam,

for sure there is improvement in 2.0.1 but it still crashes:

# python /usr/local/IOS-XR-Maintenance-Window-Checker/ios_xr_mw_gatherer.py --file /tmp/10.96.237.65.txt --ipv4addr 10.96.237.65 --username jordan.ostrev --ssh
Filename: /tmp/10.96.237.65.txt
Proceeding with login to router
Please enter your password:
Command 1 of 38 complete
Command 2 of 38 complete
Command 3 of 38 complete
Command 4 of 38 complete
Command 5 of 38 complete
Command 6 of 38 complete
Command 7 of 38 complete
Command 8 of 38 complete
Command 9 of 38 complete
Command 10 of 38 complete
Command 11 of 38 complete
Command 12 of 38 complete
Command 13 of 38 complete
Command 14 of 38 complete
Command 15 of 38 complete
Command 16 of 38 complete
Command 17 of 38 complete
Command 18 of 38 complete
Command 19 of 38 complete
Command 20 of 38 complete
SSH error <pexpect.pty_spawn.spawn object at 0x80126cd90>
command: /usr/bin/ssh
args: ['/usr/bin/ssh', 'jordan.ostrev@10.96.237.65']
buffer (last 100 chars): b', threshold: 75%\r\n MAC port down flush: enabled\r\n MAC Secure: disabled, Logging: disabled\r'
before (last 100 chars): b', threshold: 75%\r\n MAC port down flush: enabled\r\n MAC Secure: disabled, Logging: disabled\r'
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 31022
child_fd: 6
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
 0: re.compile(b'RP\\S+#')
<pexpect.pty_spawn.spawn object at 0x80126cd90>
command: /usr/bin/ssh
args: ['/usr/bin/ssh', 'jordan.ostrev@10.96.237.65']
buffer (last 100 chars): b', threshold: 75%\r\n MAC port down flush: enabled\r\n MAC Secure: disabled, Logging: disabled\r'
before (last 100 chars): b', threshold: 75%\r\n MAC port down flush: enabled\r\n MAC Secure: disabled, Logging: disabled\r'
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 31022
child_fd: 6
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
 0: re.compile(b'RP\\S+#')

Regards,
--
Jordan Ostreff
Sent with Spark

**Comment by smilstea** [comment]
Ok that's 'show l2vpn bridge detail', it's probably failing because the
output is so huge, we can try increasing the timeout for the expect.
Try changing line 172 to this: connection.expect([r'RP\S+#'], timeout=300)
We can try larger is need-be depending on your scale for l2vpn, one way to
check would be to run the command in a regular ssh session and time it.

Sam

**Comment by smilstea** [comment]
Actually it's less likely to be a timeout and more likely to be a buffering
issue, instead try modifying line 127:
connection = pexpect.spawn('ssh %s@%s' % (username, ipv4_addr),
timeout=300, maxread=1)
this will change the timeout session wide and also disable buffering, by
default the limit for buffering data from the TTY session is 2000 bytes,
there is a limit of 4096 max, or you can disable buffering with it set to
1. This will ensure all the output is gathered and that we don't run out of
time as well.

Sam

**Comment by jostreff** [comment]
Hi Sam,

changed line 127 as you have proposed ( it’s attached in the picture ). The result is not positive - you can see bellow.

Also have checked the output via ssh of "show l2vpn bridge detail” command on same device - it’s 69840 lines long. I can provide it to you via email, but not on this emails which publish everything on GitHub ticket.

# python /usr/local/IOS-XR-Maintenance-Window-Checker/ios_xr_mw_gatherer.py --file /tmp/10.96.237.65.txt --ipv4addr 10.96.237.65 --username jordan.ostrev --ssh
Filename: /tmp/10.96.237.65.txt
Proceeding with login to router
Please enter your password:
Command 1 of 38 complete
Command 2 of 38 complete
Command 3 of 38 complete
Command 4 of 38 complete
Command 5 of 38 complete
Command 6 of 38 complete
Command 7 of 38 complete
Command 8 of 38 complete
Command 9 of 38 complete
Command 10 of 38 complete
Command 11 of 38 complete
Command 12 of 38 complete
Command 13 of 38 complete
Command 14 of 38 complete
Command 15 of 38 complete
Command 16 of 38 complete
Command 17 of 38 complete
Command 18 of 38 complete
Command 19 of 38 complete
Command 20 of 38 complete
SSH error <pexpect.pty_spawn.spawn object at 0x80126cd90>
command: /usr/bin/ssh
args: ['/usr/bin/ssh', 'jordan.ostrev@10.96.237.65']
buffer (last 100 chars): b'%\r\n MAC port down flush: enabled\r\n MAC Secure: disabled, Logging: disabled\r\n Split Ho'
before (last 100 chars): b'%\r\n MAC port down flush: enabled\r\n MAC Secure: disabled, Logging: disabled\r\n Split Ho'
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 9344
child_fd: 6
closed: False
timeout: 300
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 1
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
 0: re.compile(b'RP\\S+#')
<pexpect.pty_spawn.spawn object at 0x80126cd90>
command: /usr/bin/ssh
args: ['/usr/bin/ssh', 'jordan.ostrev@10.96.237.65']
buffer (last 100 chars): b'%\r\n MAC port down flush: enabled\r\n MAC Secure: disabled, Logging: disabled\r\n Split Ho'
before (last 100 chars): b'%\r\n MAC port down flush: enabled\r\n MAC Secure: disabled, Logging: disabled\r\n Split Ho'
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 9344
child_fd: 6
closed: False
timeout: 300
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 1
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
 0: re.compile(b'RP\\S+#')

Regards,
--
Jordan Ostreff
Sent with Spark

**Comment by smilstea** [comment]
I made a 165k line output for show l2vpn bridge det in my lab just now and
can see the same problem, I switched to no timeout (timeout=None) and it
still fails to complete the command. But I know why now, anything over a
certain number of bytes cannot be read and parsed for an expect statement
all at once so we have to read in sections until there is nothing more to
read. I set the timeout to 10s, so that means the time it takes each
command to complete there will be a 10s delay before the script finishes
parsing that output for each command; the reason for this is because not
every command will immediately respond to a show command so we need a small
delay for that, but also some of the CRS fabric commands pause half-way
into the output for a few seconds and I don't want to break that
output.There is also one small change to the comparer script. I uploaded
the changes to github.

Sam

**Comment by jostreff** [comment]
Hi Sam,
After your last changes -  the scripts are running correctly in my environment. Thanks for your effort!

# python /usr/local/IOS-XR-Maintenance-Window-Checker/ios_xr_mw_gatherer.py --file /tmp/10.96.237.65.txt --ipv4addr 10.96.237.65 --username jordan.ostrev --ssh
Filename: /tmp/10.96.237.65.txt
Proceeding with login to router
Please enter your password:
Command 1 of 38 complete
Command 2 of 38 complete
Command 3 of 38 complete
Command 4 of 38 complete
Command 5 of 38 complete
Command 6 of 38 complete
Command 7 of 38 complete
Command 8 of 38 complete
Command 9 of 38 complete
Command 10 of 38 complete
Command 11 of 38 complete
Command 12 of 38 complete
Command 13 of 38 complete
Command 14 of 38 complete
Command 15 of 38 complete
Command 16 of 38 complete
Command 17 of 38 complete
Command 18 of 38 complete
Command 19 of 38 complete
Command 20 of 38 complete
Command 21 of 38 complete
Command 22 of 38 complete
Command 23 of 38 complete
Command 24 of 38 complete
Command 25 of 38 complete
Command 26 of 38 complete
Command 27 of 38 complete
Command 28 of 38 complete
Command 29 of 38 complete
Command 30 of 38 complete
Command 31 of 38 complete
Command 32 of 38 complete
Command 33 of 38 complete
Command 34 of 38 complete
Command 35 of 38 complete
Command 36 of 38 complete
Command 37 of 38 complete
Command 38 of 38 complete


My last advice if you want it - made the *.py scripts executable by putting at the beggining
#!/usr/bin/env python

Regards,
--
Jordan Ostreff
Sent with Spark
